# Generated by Django 3.x on 2026-??-??
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_file_question_image_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_matching',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
