# Generated by Django 5.0.6 on 2026-03-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_materialreadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text="Testni yopish vaqti (bo'sh=cheksiz)", null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text="Testni boshlash vaqti (bo'sh=darhol)", null=True),
        ),
    ]
