# Generated by Django 5.0.6 on 2026-04-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_classroom_material_classroom_test_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='youtube_url',
            field=models.URLField(blank=True, help_text="YouTube video havolasi (fayl o'rniga)", null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
