# Generated by Django 5.0.6 on 2026-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_material_youtube_url_alter_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='total_xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
