# Generated by Django 5.0.6 on 2026-04-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_level_user_total_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('youtube', 'YouTube'), ('image', 'Rasm'), ('word', 'Word'), ('ppt', 'PPTX')], max_length=10),
        ),
    ]
