# Generated by Django 5.0.6 on 2026-05-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_material_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, help_text='Mavzu nomi (Analytics uchun kerak)', max_length=100, null=True),
        ),
    ]
