# Generated by Django 5.0.6 on 2026-05-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_live',
            field=models.BooleanField(default=False, help_text="Hozi jonli dars bo'lyaptimi"),
        ),
    ]
