# Generated by Django 5.0.6 on 2026-05-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_classroom_is_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='is_live',
        ),
    ]
