# Generated by Django 5.0.6 on 2026-05-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_classroom_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_text',
            field=models.CharField(blank=True, help_text='Used for graph or text input answers', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_text',
            field=models.CharField(blank=True, help_text='Used for text input or graph math equations.', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Koʻp variantli'), ('matching_pairs', 'Juftlashtirish'), ('draw_graph', 'Grafik chizish'), ('find_equation', 'Funksiyani topish')], default='multiple_choice', max_length=20),
        ),
    ]
