# Generated by Django 5.0.6 on 2026-05-20 18:50

from django.db import migrations, models


def populate_emails(apps, schema_editor):
    User = apps.get_model('api', 'User')
    for user in User.objects.filter(models.Q(email='') | models.Q(email__isnull=True)):
        user.email = f"{user.username}@example.com"
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_answer_selected_text_question_correct_answer_text_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_emails),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
