# Generated by Django 5.0.6 on 2026-05-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='access_type',
            field=models.CharField(choices=[('public', 'Ochiq'), ('class', 'Faqat sinf')], default='class', max_length=10),
        ),
    ]
