# Generated by Django 5.0.6 on 2026-06-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_material_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='AI feedback on student performance', null=True),
        ),
    ]
